import json
import time
import urllib.request
import urllib.error

# ================= 配置区 (Configuration) =================

# 1. 飞书机器人的 Webhook 地址
# [动作]: 请去飞书群组 -> 设置 -> 群机器人 -> 添加机器人 -> 自定义机器人 -> 复制 Webhook 地址
# 格式长这样: "https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
FEISHU_WEBHOOK_URL = "https://open.feishu.cn/open-apis/bot/v2/hook/340353ef-39df-4477-b06a-817fc33f3362"

# 2. 想要抓取的新闻数量
NEWS_LIMIT = 5

# ================= 辅助功能 (Helpers) =================

def log_message(message):
    """
    记录日志到本地文件 (bot.log)
    这样即使脚本在后台运行，我们也能知道发生了什么
    """
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    log_line = f"[{timestamp}] {message}"
    print(log_line) # 同时也打印到控制台
    
    # 追加模式 ('a') 写入文件
    try:
        with open("bot_history.log", "a", encoding="utf-8") as f:
            f.write(log_line + "\n")
    except Exception as e:
        print(f"日志写入失败: {e}")

# ================= 核心工具 (The Engine) =================

def fetch_hacker_news():
    """
    从 Hacker News 获取前 N 条热门科技新闻
    """
    log_message("📡 正在连接 Hacker News 获取最新资讯...")
    
    news_list = []
    
    try:
        # 1. 获取 Top Stories 的 ID 列表
        top_stories_url = "https://hacker-news.firebaseio.com/v0/topstories.json"
        with urllib.request.urlopen(top_stories_url) as response:
            story_ids = json.loads(response.read().decode())

        # 2. 只要前 N 个
        target_ids = story_ids[:NEWS_LIMIT]

        # 3. 循环获取每个故事的详情
        for sid in target_ids:
            item_url = f"https://hacker-news.firebaseio.com/v0/item/{sid}.json"
            with urllib.request.urlopen(item_url) as item_resp:
                story = json.loads(item_resp.read().decode())
                
                # 提取我们需要的信息：标题 和 链接
                title = story.get('title', 'No Title')
                url = story.get('url', 'https://news.ycombinator.com')
                
                print(f"   Found: {title[:30]}...")
                news_list.append(f"• [{title}]({url})")
                
    except Exception as e:
        log_message(f"❌ 获取新闻失败: {e}")
        return None

    return news_list

def send_to_feishu(content_list):
    """
    把整理好的内容推送到飞书
    """
    if not content_list:
        log_message("⚠️ 没有内容可以发送。")
        return

    log_message(f"🚀 正在推送 {len(content_list)} 条新闻到飞书...")

    # 1. 构造飞书卡片消息 (Markdown 格式)
    # 飞书机器人文档: https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/im-v1/message/create_json
    
    # 拼接新闻内容，用换行符分隔
    text_content = "\n\n".join(content_list)
    
    # 加上标题和落款
    full_text = f"📢 **每日科技早报 (Daily Tech)**\n\n{text_content}\n\n_Generated by Python Script_"

    # 构造请求数据
    payload = {
        "msg_type": "interactive",
        "card": {
            "header": {
                "title": {
                    "tag": "plain_text",
                    "content": "🔥 行业资讯速递"
                },
                "template": "blue"
            },
            "elements": [
                {
                    "tag": "div",
                    "text": {
                        "tag": "lark_md",
                        "content": text_content
                    }
                },
                {
                    "tag": "hr"
                },
                {
                    "tag": "note",
                    "elements": [
                        {
                            "tag": "plain_text",
                            "content": f"来自 Hacker News • {time.strftime('%Y-%m-%d %H:%M')}"
                        }
                    ]
                }
            ]
        }
    }

    # 2. 发送请求 (POST)
    # 如果用户没有填写真实的 Webhook，这里会拦截
    if "你的_WEBHOOK" in FEISHU_WEBHOOK_URL:
        print("\n🛑 【停止】你还没有配置 Webhook URL！")
        print("请打开脚本文件，在第 9 行填入你的飞书机器人地址。")
        print("预览消息内容如下：")
        print("-" * 30)
        print(full_text)
        print("-" * 30)
        return

    try:
        req = urllib.request.Request(
            FEISHU_WEBHOOK_URL, 
            data=json.dumps(payload).encode('utf-8'),
            headers={'Content-Type': 'application/json'}
        )
        with urllib.request.urlopen(req) as response:
            result = response.read().decode()
            log_message(f"✅ 发送成功! 飞书返回: {result}")
            
    except Exception as e:
        log_message(f"❌ 发送失败: {e}")

# ================= 主程序入口 =================

if __name__ == "__main__":
    log_message("=== 脚本开始运行 ===")
    # 1. 获取新闻
    news = fetch_hacker_news()
    
    # 2. 推送飞书
    send_to_feishu(news)
    log_message("=== 脚本运行结束 ===")
